config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'categories/show'

  ActiveAdmin.routes(self)

  get 'orders/index'

  get 'orders/new'

  get 'orders/create'

  get 'orders/show'

  get 'orders/confirm_orders'

  get 'sessions/logout'

  get 'sessions/login'

  post 'sessions' => 'sessions#create'

  get 'registration' => 'users#new', as: 'registration'

  post 'users' => 'users#create'

  resources :products do
    resources :comments
    member do
      post 'add_to_cart'
      post 'vote'
    end
  end

  resources :categories, only: [:show, :index]
  resources :users, only: [:show, :edit, :update]

  root 'products#index'
  get 'cart' => 'products#show_cart'
  get 'clear_cart' => 'products#clear_cart'
  get 'results', to: 'results#index', as: 'results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  sname           :string
#  email           :string
#  password_digest :string
#  phone           :string
#  country         :string
#  city            :string
#  street          :string
#  number          :integer
#  appartament     :integer
#  postindex       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  role            :string
#  image           :string
#

class User < ApplicationRecord
  has_secure_password

  has_many :orders
  has_many :comments
  has_many :assessments

  validates :password_digest, length:{minimum: 6}
  validates :email, uniqueness: true
  validates :name, :sname, :email, :password_digest, presence: true

  mount_uploader :image, UsersAvatarUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :update

  def show
    user_id = params[:id]
    if user_id.to_i == current_user.id
      @user = User.find(user_id)
    else
      redirect_to root_path, notice: 'Вы не можете перейти на эту страницу'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.role = 'user'
    if @user.save
      redirect_to :back
      current_user
    else
      redirect_to root_path, notice: 'Что-то не так'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        @user = User.find(params[:id])
        format.html { redirect_to @user, notice: 'Личные данные успешно отредактированы.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to :back, notice: 'К сожалению произошла ошибка' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :sname, :email, :password, :phone, :country, :city,
                                 :street, :number, :appartament, :postindex, :role, :image)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def count
    Check.all.where({user_id: current_user.id}).count
  end

  def users_checks
    Check.all.where({user_id: current_user.id})
  end

  def users_confirm_orders(check)
    Order.all.where({user_id: current_user.id, number: check})
  end

  def orders?
    Order.all.where({user_id: current_user.id, confirm: false}).present?
  end

  def ordercount
    Order.all.where({user_id: current_user.id, confirm: false})
  end
end

app/views/users/_edit_avatar_form.html.erb
<%= form_for user do |f| %>

  <%= image_tag 'close.png', class: 'close' %>
  <br/>
  <div class="field">
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="user_action">
    <%= f.submit 'Загрузить аватар', class: 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/_edit_form.html.erb
<%= form_for user do |f| %>

  <%= image_tag 'close.png', class: 'close' %>

  <h3>
    Измените нужные поля
  </h3>

  <div class="field">
    <%= f.label :Имя %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Фамилия %>
    <%= f.text_field :sname, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Телефон %>
    <%= f.phone_field :phone, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Страна %>
    <%= f.text_field :country, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Город %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Улица %>
    <%= f.text_field :street, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Дом %>
    <%= f.text_field :number, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Квартира %>
    <%= f.text_field :appartament, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Индекс %>
    <%= f.text_field :postindex, class: 'form-control' %>
  </div>

  <div class="user_action">
    <%= f.submit 'Редактировать личные данные', class: 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/_form.html.erb
<% @user = User.new %>
<%= form_for (@user) do |f| %>

  <div class="field">
    <%= f.label :Имя %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Фамилия %>
    <%= f.text_field :sname, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Телефон %>
    <%= f.phone_field :phone, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Страна %>
    <%= f.text_field :country, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Город %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Улица %>
    <%= f.text_field :street, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Дом %>
    <%= f.text_field :number, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Квартира %>
    <%= f.text_field :appartament, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :Индекс %>
    <%= f.text_field :postindex,class: 'form-control' %>
  </div>

  <div class="user_action">
    <%= f.submit 'Создать аккаунт', class: 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/edit.js.erb
<% if params[:avatar].present? %>
  $('.avatar').after('<%= j render 'edit_avatar_form', user: current_user %>');
<% else %>
  $('.avatar').after('<%= j render 'edit_form', user: current_user %>');
<% end %>

app/views/users/new.html.erb
<div class="container">
<h1>
  Регистрация
</h1>
<p>
  Пожалуйста зарегестрируйтесь или <%= link_to 'войдите в свой аккаунт', sessions_login_path %>
</p>
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="avatar">
  <h3>
    <%= @user.name %>
    <%= @user.sname %>
  </h3>
  <% if @user.image.blank? %>
    <%= image_tag 'none_avatar.jpg' %>
  <% else %>
    <%= image_tag @user.image_url %>
  <% end %>
  <br/>
  <%= link_to 'Редактировать личные данные', edit_user_path(@user), id: 'edit_user_link', remote: true %>
  <br/>
  <%= link_to 'Загрузить новый аватар', edit_user_path(@user, avatar: '1'), id: 'new_avatar_link', remote: true %>
</div>
<div class="orders">
  <% if checks? %>
    <h3>
      Подтвержденные заказы
    </h3>
    <% if count == 1 %>
      <p>
        Дата заказа:
        <%= users_check.date %>
        <span>
          Код заказа:
          <%= users_check.number %>
        </span>
      </p>
      <%= product_name(users_confirm_order(users_check.number).product_id) %>
      <%= users_confirm_order(users_check.number).sum %>
    <% else %>
      <% users_checks.find_each do |check| %>
        <p>
          Дата заказа:
          <%= check.date %>
          <span>
          Код заказа:
            <%= check.number %>
        </span>
        </p>
        <% users_confirm_orders(check.number).find_each do |order| %>
          <%= product_name(order.product_id) %>
          <%= order.sum %>
          <br/>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <% if orders? %>
    <h3>
      Неподтвержденные заказы
    </h3>
    <% ordercount.find_each do |order| %>
      <p>
        Дата заказа:
        <%= order.date %>
      </p>
      <%= product_name(order.product_id) %>
      <%= order.amount %>
      <%= order.sum %>
    <% end %>
    <p>
      <%= button_to 'Подтвердить заказы', orders_show_path, method: :get, class: 'btn btn-primary' %>
    </p>
  <% end %>
  <% if cookies[:cart].present? %>
    <h3>
      Товары в корзине
    </h3>
    <% cookies[:cart].split(',').each do |id| %>
      <%= product_name(id) %>
    <% end %>
    <p>
      <%= button_to 'Купить!', cart_path, method: :get, class: 'btn btn-primary' %>
    </p>
  <% end %>
</div>