config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'categories/show'

  ActiveAdmin.routes(self)

  get 'orders/index'

  get 'orders/new'

  get 'orders/create'

  get 'orders/show'

  get 'orders/confirm_orders'

  get 'sessions/logout'

  get 'sessions/login'

  post 'sessions' => 'sessions#create'

  get 'registration' => 'users#new', as: 'registration'

  post 'users' => 'users#create'

  resources :products do
    resources :comments
    member do
      post 'add_to_cart'
      post 'vote'
    end
  end

  resources :categories, only: [:show, :index]
  resources :users, only: [:show, :edit, :update]

  root 'products#index'
  get 'cart' => 'products#show_cart'
  get 'clear_cart' => 'products#clear_cart'
  get 'results', to: 'results#index', as: 'results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id             :integer          not null, primary key
#  name           :string
#  position       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  hasDescendands :boolean
#  hasAncestor    :boolean
#

class Category < ApplicationRecord
  acts_as_list

  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, :position, presence: true
  validates :name, uniqueness: true

  scope :sorted, -> {order(:position)}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
     @categories = Category.all.sorted
  end

  def show
    @categories = Category.all.sorted
    category_id = params[:id]
    @products = ProductCategory.all.where({category_id: category_id})
    @products.page(params[:page])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def ancestor?(category)
    category.hasAncestor == false
  end

  def descendant?(category)
    category.hasDescendands == true
  end

  def print_descendants(category)
    DescendantCategory.all.where({parent: category.id})
  end
end

app/helpers/concerns/categories_helper.rb
module Concerns::CategoriesHelper
end

app/views/categories/_categories.html.erb
<ul>
  <% @categories.each do |category| %>
    <% if ancestor?(category) %>
      <li class="category">
        <%= link_to category.name, category %>
      </li>
      <% if descendant?(category)%>
        <ul>
        <% print_descendants(category).each do |descendant| %>
          <li class="category l2">
            <%= link_to find_category(descendant.category_id), category_path(id: descendant.category_id)%>
          </li>
        <% end %>
        </ul>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/categories/show.html.erb
<div class="categories col-sm-2 col-md-2 col-lg-2">
  <h3>
    Категории:
  </h3>
  <%= render 'categories/categories' %>
  <br>
</div>
<h3 class="title">
  Категория <%= find_category(params[:id]) %>
</h3>
<% @products.each do |product| %>
  <%= render partial: 'products/product', locals: {product: find_products(product.product_id)} %>
<% end %>