config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'categories/show'

  ActiveAdmin.routes(self)

  get 'orders/index'

  get 'orders/new'

  get 'orders/create'

  get 'orders/show'

  get 'orders/confirm_orders'

  get 'sessions/logout'

  get 'sessions/login'

  post 'sessions' => 'sessions#create'

  get 'registration' => 'users#new', as: 'registration'

  post 'users' => 'users#create'

  resources :products do
    resources :comments
    member do
      post 'add_to_cart'
      post 'vote'
    end
  end

  resources :categories, only: [:show, :index]
  resources :users, only: [:show, :edit, :update]

  root 'products#index'
  get 'cart' => 'products#show_cart'
  get 'clear_cart' => 'products#clear_cart'
  get 'results', to: 'results#index', as: 'results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(8, 2)    default(0.0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string
#  rating      :float
#

class Product < ApplicationRecord
  include PgSearch
  pg_search_scope :search_everywhere, against: [:name, :description]

  paginates_per 8

  scope :best, -> { where('rating >= 4.5')}

  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :comments
  has_many :assessments

  validates :name, :price, presence: true
  validates :name, uniqueness: true

  mount_uploader :image, ProductImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).best
    @categories = Category.all.sorted
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    product_id = params[:id]
    if cookies[:cart].present? == false
      cookies[:cart] = product_id
    end
    if can_add_to_cart?
      products = cookies[:cart].split(',')
      products << product_id
      cookies[:cart] = products.join(',')
    end
    redirect_to root_path
  end

  def show_cart
    @products = Product.page(params[:page]).best
    if cookies[:cart].present?
      cookies[:cart].split(',').each do |product|
        @sum = @sum.to_f + Product.find(product).price
      end
      @count_of_products = cookies[:cart].split(',').size
    else
      @count_of_products = 0
    end
  end

  def clear_cart
    cookies.delete :cart
    redirect_to root_path
  end

  def can_add_to_cart?
    if cookies[:cart].present? && cookies[:cart].split(',').include?(params[:id])
      false
    else
      true
    end
  end

  def vote
    if current_user && can_user_vote?
      case params[:vote]
        when '1'
          value = 1
        when '2'
          value = 2
        when '3'
          value = 3
        when '4'
          value = 4
        when '5'
          value = 5
      end
      @product = Product.find(params[:id])
      assessment = Assessment.new
      assessment.user = current_user
      assessment.product = @product
      assessment.value = value
      assessment.save
    else redirect_to :back, notice: 'Вы не можете поставить оценку'
    end
  end

  private

  def can_user_vote?
    @rated_by = Assessment.where(user_id: current_user.id, product_id: params[:id])
    @rated_by.blank?
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def count_assessments(product)
    product.assessments.count
  end
end

app/views/products/_product.html.erb
<div class="col-lg-3 col-md-6 mb-4 col-xs-12">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title"><%=link_to product.name, product %></h3>
      <br/>
      <%= link_to ((image_tag product.image_url(:thumb) unless product.image.blank?)), product if product.image %>
      <br/>
      <%= number_to_currency(product.price, unit: 'грн.', format: '%n %u') %>
      <br/>
    </div>
    <div class="card-footer">
      <%= button_to 'Добавить в корзину', add_to_cart_product_path(product), class: "btn btn-primary" %>
      <br>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="categories col-sm-2 col-md-2 col-lg-2">
  <h3>
    Категории:
  </h3>
  <%= render 'categories/categories' %>
  <br>
</div>
<h3 class="title">
  Лучшие товары
</h3>
<%= render @products %>
<br>
<div class="pagination">
  <%= paginate @products %>
</div>

app/views/products/show.html.erb
<div class="product">
<h2>
  <%= @product.name %>
</h2>
  <br/>
  <%= link_to (image_tag ('star1.png')), vote_product_path(@product, vote: 1), method: :post, remote: true %>
  <%= link_to (image_tag ('star1.png')), vote_product_path(@product, vote: 2), method: :post,remote: true %>
  <%= link_to (image_tag ('star1.png')), vote_product_path(@product, vote: 3), method: :post,remote: true %>
  <%= link_to (image_tag ('star1.png')), vote_product_path(@product, vote: 4), method: :post,remote: true %>
  <%= link_to (image_tag ('star1.png')), vote_product_path(@product, vote: 5), method: :post,remote: true %>
  <span>
    Рейтинг товара:
    <%= @product.rating %>
  </span>
  <span>
    (Количеcтво голосов:
    <%= count_assessments(@product) %>
    )
  </span>
  <br/>
<%= image_tag @product.image_url %>
<h2>
  Цена: <%= number_to_currency(@product.price, unit: 'грн.', format: '%n %u') %>
</h2>
<%= button_to 'Добавить в корзину', add_to_cart_product_path(@product), class: "btn btn-primary" %>
</div>
<div class="description">
<p>
  <%= @product.description %>
</p>
<h2>
  Отзывы:
</h2>
<div class="comments">
  <%= render @product.comments %>
</div>
<% if current_user %>
  <h2>
    Добавить отзыв:
  </h2>
  <%= render 'comments/form_for_comments' %>
<% end %>
</div>
<%= link_to 'Назад', root_path %>

app/views/products/show_cart.html.erb
<div class="cart">
  <h1>
    Корзина
  </h1>
  <% if @count_of_products == 0%>
    <h3>
      Корзина пуста
    </h3>
    <h3>
      Вы можете выбрать что-то из наших лучших товаров:
    </h3>
    <div class="products">
      <%= render @products %>
    </div>
  <% else %>
    <h4>
      Количество товара в корзине <%= @count_of_products %>
    </h4>
  <% end %>
  <% if cookies[:cart].present? %>
    <% if current_user.present? %>
      <%= form_tag(orders_create_path, method: 'get') do %>
        <% cookies[:cart].split(',').each do |id| %>
          <%= find_products(id).name.to_s %>
          <%= find_products(id).price.to_s %>
          <br/>
          <%=label_tag 'Введите количестов товара' %>
          <%= text_field_tag id, '1', maxlength: 20%>
          <br/>
        <% end %>
        <br/>
        <%= submit_tag 'Оформить заказ!', class: 'btn btn-primary', data: { confirm: 'Вы уверены?' } %>
      <% end %>
    <% else %>
      <% cookies[:cart].split(',').each do |id| %>
        <%= find_products(id).name.to_s %>
        <%= find_products(id).price.to_s %>
        <br/>
        <%=label_tag 'Введите количестов товара' %>
        <%= text_field_tag id ,'1', maxlength: 20%>
        <br/>
      <% end %>
      <%= button_to 'Оформить заказ!', registration_path,  method: :get, class: 'btn btn-primary' %>
    <% end %>
    <br/>
    <h4>
      Общая сумма корзины <%= @sum %>
    </h4>
    <%= button_to 'Очистить корзину', clear_cart_path, method: :get, class: 'btn btn-primary' %>
  <% end %>
</div>