config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'categories/show'

  ActiveAdmin.routes(self)

  get 'orders/index'

  get 'orders/new'

  get 'orders/create'

  get 'orders/show'

  get 'orders/confirm_orders'

  get 'sessions/logout'

  get 'sessions/login'

  post 'sessions' => 'sessions#create'

  get 'registration' => 'users#new', as: 'registration'

  post 'users' => 'users#create'

  resources :products do
    resources :comments
    member do
      post 'add_to_cart'
      post 'vote'
    end
  end

  resources :categories, only: [:show, :index]
  resources :users, only: [:show, :edit, :update]

  root 'products#index'
  get 'cart' => 'products#show_cart'
  get 'clear_cart' => 'products#clear_cart'
  get 'results', to: 'results#index', as: 'results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <nav class = "navbar  navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class = "nav navbar-nav">
            <li class="active">
              <%= link_to 'На главную', root_path, class: "navbar-link" %>
            </li>
            <li class="active">
              <%= link_to 'Корзина', cart_path, class: "navbar-link" %>
            </li>
            <%unless current_user%>
              <li class="active">
                <%= link_to 'Registration', registration_path, class: "navbar-link" %>
              </li>
              <li class="active">
                <%= link_to 'Log In', sessions_login_path, class: "navbar-link" %>
              </li>
            <%else%>
              <li class="active">
                <%= link_to 'Log Out', sessions_logout_path, class: "navbar-link" %>
              </li>
            <%end%>
            <li class="active">
              <%= link_to current_user.name, user_path(id: current_user), class: "navbar_link" if current_user%>
            </li>
          </ul>
          <%= form_tag( results_path, method: :get, role: 'search', :class => 'search') do %>
            <div class="form-row">
              <div class="form-group col-md-10">
                <%= text_field_tag :query, params[:query], maxlength: 20, placeholder:"Искать здесь...", class:"form-control" %>
              </div>
              <div class="form-group col-md-2">
                <%= submit_tag 'Найти', class: 'btn btn-primary'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
    <%= yield %>
    <div class="footer">
      <%= render 'application/footer' %>
    </div>
  </body>
</html>